<a href="https://colab.research.google.com/github/DAYACHAND-PRAJAPAT/DL-using-Colab/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors Creation

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())

2.8.0+cu126
False
0


In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
a = torch.zeros(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.6845, 0.0972, 0.3927],
        [0.4996, 0.0192, 0.5096]])

In [ ]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3,4],[5,6,7,8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
# using linespace
torch.linspace(0,10,20)

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

Tensors Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x.shape

torch.Size([3, 3])

In [ ]:
torch.empty_like(x)

tensor([[3616445622929465956, 6067247193300938037, 3832908753774720305],
        [6500159044537495854, 7309453675965983778, 8315168162784306286],
        [8367752027310484831, 7954801838398993778, 2459029315949324647]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Tensor Data Types

In [ ]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

Reduction Operation

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 8., 4.],
        [4., 1., 0.]])

In [ ]:
torch.sum(e)

tensor(25.)

In [ ]:
torch.sum(e,dim=0)

tensor([12.,  9.,  4.])

In [ ]:
torch.sum(e,dim=1)

tensor([20.,  5.])

In [ ]:
torch.mean(e)

tensor(4.1667)

In [ ]:
torch.mean(e,dim=0)

tensor([6.0000, 4.5000, 2.0000])

In [ ]:
torch.median(e)

tensor(4.)

In [ ]:
torch.prod(e)

tensor(0.)

Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])
tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])


In [ ]:
m + n

tensor([[1.4812, 0.9536, 0.9538],
        [1.3137, 0.5332, 0.2568]])

In [ ]:
m.add_(n)
print(m)

tensor([[1.4812, 0.9536, 0.9538],
        [1.3137, 0.5332, 0.2568]])


Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

In [ ]:
b = a
b

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

In [ ]:
print(id(a))

id(b)

138833871247216


138833871247216

In [ ]:
b = a.clone()
print(id(a))
print(id(b))

138833871247216
138833871187120


Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b


tensor([[[0.9454, 0.7116, 0.1157, 0.6574],
         [0.3451, 0.0453, 0.9798, 0.5548],
         [0.6868, 0.4920, 0.0748, 0.9605]],

        [[0.3271, 0.0103, 0.9516, 0.2855],
         [0.2324, 0.9141, 0.7668, 0.1659],
         [0.4393, 0.2243, 0.8935, 0.0497]]])

In [ ]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
c = torch.rand(226,226,3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [ ]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])